sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $token
    on:
        branch: master
    local_dir: public
    repo: skycity233/Blog
    fqdn: <custom-domain-if-needed>
    target_branch: master
    email: 544907049@qq.com
    name: skycity233